[package]
title = "Smart Physics Setup"
id = "tw.zin.smart_physics_setup"
version = "0.1.0"
description = "A tool to setup physics properties quickly."
authors = ["Zin"]
repository = ""
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
keywords = ["physics", "utils"]
category = "ZinTools"

icon = "data/SMART_PHYSICS_SETUP.png"
preview_image = "data/preview.png"

# 【關鍵修改】在這裡加入其他工具的 ID
[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.uiapp" = {}

[[python.module]]
name = "smart_physics_setup"
