[package]
title = "SmartReference"
version = "0.1.0"
description = "Zin All Tools suite for automated assembly from BOM."
authors = ["Zin"]
readme = "README.md"
repository = "https://github.com/<YOUR_GITHUB>/<YOUR_REPO>"
keywords = [
    "omniverse",
    "kit",
    "extension",
    "tw.zin",
    "bom",
    "usd",
    "automation",
]
category = "ZinTools"

[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.pipapi" = {}

[[python.pipapi.dependencies]]
"pandas" = {}
"openpyxl" = {} # 讀取 Excel 檔案 (.xlsx) 必須安裝這個

[python.pip]
packages = ["pandas", "openpyxl"]

[[python.module]]
name = "smart_reference"
class = "SmartReferenceExtension" # 這裡必須與 extension.py 裡的類別名一模一樣
